// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHRNgJXITkDxLhyKH06xzfJgFIt5ph4w',
    appId: '1:1006402812002:web:a3c2ac6a8626aac641393b',
    messagingSenderId: '1006402812002',
    projectId: 'assignment-threads',
    authDomain: 'assignment-threads.firebaseapp.com',
    storageBucket: 'assignment-threads.appspot.com',
    measurementId: 'G-MZ41CE9ZCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFIWyxtR3OzwlFzJ0z1s1ZKGzJiHZYm4',
    appId: '1:1006402812002:android:e1d914f2d3c825b641393b',
    messagingSenderId: '1006402812002',
    projectId: 'assignment-threads',
    storageBucket: 'assignment-threads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKOa_X9rzL1EUkiEhRQ67jpMnoMDgWE7o',
    appId: '1:1006402812002:ios:5db32ed80c05845b41393b',
    messagingSenderId: '1006402812002',
    projectId: 'assignment-threads',
    storageBucket: 'assignment-threads.appspot.com',
    iosBundleId: 'com.example.assignment13',
  );

}