class Interests {
  Interests({required this.main, required this.sub});

  final String main;
  final List<String> sub;
}

final List<Interests> interests = [
  Interests(main: "Fashion & beauty", sub: [
    "Nail arts",
    "Hair styling",
    "Skincare",
    "Fashion show",
    "Makeup",
    "Fashion history",
    "Celebrity fashion",
    "Sustainable fashion",
    "Body positive",
  ]),
  Interests(main: "Outdoor", sub: [
    "Sports climbing",
    "Camping",
    "Hiking",
    "Wildlife photography",
    "Adventure travel stories",
    "Outdoor photography tips",
    "Landscape painting",
  ]),
  Interests(main: "Arts & culture", sub: [
    "Painting",
    "Musical",
    "Ballet",
    "Theater reviews",
    "Museum exhibitions",
    "Concert",
    "Dance performances",
    "Art history",
  ]),
  Interests(main: "Animation & comics", sub: [
    "Comic con",
    "Webcomic recommendations",
    "Character design",
    "Disney",
    "Pixar",
    "DreamWorks",
    "Sony",
    "Webtoons",
    "Studio LICO",
    "Studio Ghibli",
  ]),
  Interests(main: "Business & finance", sub: [
    "Real estate",
    "Personal finance tips",
    "International Business",
    "Entrepreneurship",
    "Start-up case studies",
    "Financial Services",
    "Economic trends",
    "Stocks",
    "Invest",
  ]),
  Interests(main: "Food", sub: [
    "Nutrition tips",
    "K-food",
    "Baking techniques",
    "Gluten-free",
    "Recipe collections",
    "Food photography",
    "Cooking tutorials",
    "Restaurant reviews",
    "Diet recipes",
  ]),
  Interests(main: "Animal", sub: [
    "Dog",
    "Cat",
    "Pet care guides",
    "Pet-food",
    "Animal welfare",
    "Pet adoption",
    "Animal hospital",
    "Animal Training",
    "Veterinary advice",
  ]),
  Interests(main: "Travel", sub: [
    "Travel photography",
    "Backpacking hacks",
    "Solo travel experiences",
    "Luxury travel reviews",
    "Budget Travel Tips",
    "Hidden Gem",
    "Cultural Immersion",
  ]),
  Interests(main: "Entertainment", sub: [
    "Anime",
    "Marvel Universe",
    "DC Universe",
    "Moives",
    "Star Wars",
    "Star Trek",
    "Grammy Awards",
    "Movie news",
    "Harry Potter",
    "The Lord of the Rings",
  ]),
  Interests(main: "Music", sub: [
    "Rap",
    "R&B & soul",
    "Pop",
    "K-pop",
    "Music news",
    "Grammy Awards",
    "Music industry",
    "EDM",
    "Hip hop",
    "Reggae",
    "Jazz",
  ]),
  Interests(main: "Gaming", sub: [
    "League of Legends",
    "Esports",
    "Playstation",
    "Epic games",
    "EA",
    "Retro games",
    "Gaming industry news",
    "Minecraft",
    "GTA 5",
    "Roblox",
  ]),
];
